endpoints/api_config.py
endpoints/swagger_generator.py
endpoints/test/discovery_service_test.py
endpoints/test/swagger_generator_test.py
endpoints/test/test_util.py
endpoints/util.py

If the config is being generated locally (using endpointscfg.py), we stick to the old logic of "HTTP if localhost else HTTPS". When it's being generated remotely (using apiserving.py), we use the new logic: "HTTP if running on development server, else HTTPS"

Determine transfer protocol more precisely

---

endpoints/endpointscfg.py

It appears that gcloud doesn't play nice with deploying filenames with dashes or underscores in them.

Change filename of Swagger spec output

---

endpoints/apiserving.py

The removed line was already being accomplished a few lines farther down.

Remove extraneous base_paths adding

---

endpoints/discovery_generator.py
endpoints/discovery_service.py
endpoints/test/discovery_generator_test.py
endpoints/test/discovery_service_test.py

The available services were not properly being filtered for the requested api and version, which led to invalid information in the best case and exceptions in the worst case. (Or maybe those cases should be the other way around.)
Fixes #74, #70.

Handle multiple api versions properly in discovery service.

---

endpoints/test/users_id_token_test.py
endpoints/users_id_token.py

Depending on flags, get_verified_jwt will consult the Authorization header, the access_token query arg, or both.

Allow get_verified_jwt to check query args for the token.

---

endpoints/openapi_generator.py
endpoints/test/openapi_generator_test.py

Some users wanted path params to be required no matter whether manually specified as such or not.

Automatically mark path params as required.

---

endpoints/test/users_id_token_test.py
endpoints/users_id_token.py

This fixes a bug in #80 where we couldn't actually check query args due to not passing in the request. (This time it's been tested with a live app. :smile: )

get_verified_jwt requires a request to check query args

---

endpoints/api_config.py
endpoints/discovery_generator.py
endpoints/test/discovery_generator_test.py
endpoints/test/users_id_token_test.py
endpoints/users_id_token.py
requirements.txt
setup.py

We now provide the api's defined oauth scopes in the discovery doc. Additionally, scopes can be passed as an object which contains both the scope name and a description.
For example:
```python
@api(name='example', scopes=['https://www.googleapis.com/auth/santa'])
```
This lacks a description, so it will be presented to the user as that URI. Instead, we can do this:
```python
scope = OAuth2Scope(
scope='https://www.googleapis.com/auth/santa',
description='Access your letter to Santa')
@api(name='example', scopes=[scope])
```
And the description will be included in the discovery doc.

Set scopes properly in discovery doc

---

endpoints/__init__.py

Rationale:
* Discovery docs now properly contain the OAuth2 scopes
* Improved security definition generation in OpenAPI specs

Bump minor version (2.3.1 -> 2.4.0)

---

endpoints/test/conftest.py
endpoints/util.py
setup.cfg

The `is_running_on_devserver()` function was incorrectly interpreting the testbed environment (used by endpointscfg.py) as running on the dev server, causing incorrect schemes in generated docs.
This problem was masked by the test environment not using testbed.
Fixes #59. Fixes #79. Fixes #94.

Generate correct scheme in documents

---

endpoints/__init__.py
endpoints/api_config.py
endpoints/test/api_config_test.py
endpoints/test/users_id_token_test.py
endpoints/users_id_token.py

Feature request so users don't have to remember to add it to the whitelist.

Automatically allow the API Explorer client id when running locally.

---

endpoints/api_backend.py
endpoints/test/api_backend_service_test.py
endpoints/test/apiserving_test.py
endpoints/test/users_id_token_test.py
setup.py
test-requirements.txt

https://pypi.python.org/pypi/mox urges this transition.
While doing the conversion, I uncovered a few situations where mox was inadequate to detect problems (particularly having to do with the LogMessage class).

Replace the obsolete mox library with mock.

---

endpoints/discovery_generator.py
endpoints/test/discovery_generator_test.py

A user encountered a situation where a recursive message structure in the request would loop infinitely through `__field_to_subfields`. This method is used to match url patterns against message fields, so it's safe to shortcut it here; there's no need to match an infinitely deep message structure in a finite url.

Make discovery generation work reasonably with recursive structures.

---

requirements.txt
setup.py

17.3.0 introduces use of the standard library module ctypes, which is
not permitted by the App Engine sandbox. See #118.

Peg attrs library at 17.2.0.

---

endpoints/test/users_id_token_test.py

In some versions of Python (2.7.14, for instance), the act of logging
something causes time.time() to be called. We only care about calls
happening within our code.

Patch time.time() in the appropriate module.

---

endpoints/__init__.py

`endpoints.api_config.LimitDefinition` and `endpoints.api_config.Namespace` can now be accessed directly from `endpoints`.

import api_config types into endpoints namespace

---

endpoints/__init__.py

Fixes tests for versions of Python where logging.debug() was calling time.time().
Adds extra imports to the base endpoints package.

Bump subminor version (2.4.4 -> 2.4.5)

---

endpoints/_endpointscfg_impl.py
endpoints/api_config.py
endpoints/directory_list_generator.py
endpoints/discovery_generator.py
endpoints/discovery_service.py
endpoints/endpoints_dispatcher.py
endpoints/errors.py
endpoints/openapi_generator.py
endpoints/test/api_config_test.py
endpoints/users_id_token.py

Sets up a basic logger configuration (but silences certain warnings) when running endpointscfg.py
Also use named loggers everywhere, and adds a bit more detail to the ResourceContainer warning to help diagnose instances where it appears unexpectedly.

Logger configuration

---

endpoints/_endpointscfg_impl.py
endpoints/api_config.py
endpoints/api_config_manager.py
endpoints/api_request.py
endpoints/apiserving.py
endpoints/directory_list_generator.py
endpoints/discovery_generator.py
endpoints/discovery_service.py
endpoints/openapi_generator.py
endpoints/test/api_config_manager_test.py
endpoints/test/api_config_test.py
endpoints/test/apiserving_test.py
endpoints/test/directory_list_generator_test.py
endpoints/test/discovery_generator_test.py
endpoints/test/openapi_generator_test.py
requirements.txt
setup.py

Instead of using the same value for the API version as a whole and the version that appears in paths, we will now treat the values separately.
If the user specifies a [semver](https://semver.org/)-compatible version string, such as `2.2.9`, we will extract the major version and place it in paths as `v2`. If the version string is not semver-compatible, it will be placed in paths as-is.
In the future, we may allow users to specify these values separately, but we currently do not.
This will be considered breaking behavior (as it's possible, though unlikely, some people are already using semver-compatible version strings) and will require a new major version of the framework when released.

API versioning improvements

---

endpoints/users_id_token.py

This function was added in 2.7.7 and AppEngine is currently using 2.7.12, so I think we're good.

Use hmac.compare_digest to compare signatures.

---

endpoints/_endpointscfg_impl.py
endpoints/api_config.py
endpoints/openapi_generator.py
endpoints/test/api_config_test.py
endpoints/test/openapi_generator_test.py

Now the new limitation is enforced only at openapi generation time, and only if the user specifies `--x-google-api-name` on the command line.

Allow opt-in to new api name restrictions.

---

endpoints/api_config.py

This parameter is no longer documented, but is probably still in use by some codebases. It does not do anything and never has. This warning paves the way for removing it in a future version.

Add warning when auth_level is used.

---

endpoints/api_config.py
endpoints/api_config_manager.py
endpoints/api_request.py
endpoints/endpoints_dispatcher.py
endpoints/test/api_config_manager_test.py
endpoints/test/api_config_test.py
endpoints/test/apiserving_test.py
endpoints/test/integration_test.py

In some cases, users may want to match paths against the escaped REQUEST_URI environment variable instead of the PATH_INFO variable. This allows ignoring escaped slashes `%2F` for purposes of path segment splitting.
This behavior must be enabled by using `use_request_uri=True` at the api or method level.

Support matching path against REQUEST_URI (flag-enabled)

---

endpoints/api_config_manager.py

This will make it easier to spot 404s caused by requests for a valid path but with the wrong HTTP method.

Improved 'No endpoint found' message.

---

endpoints/discovery_generator.py
endpoints/test/discovery_document_test.py
endpoints/test/testdata/discovery/allfields.json
endpoints/test/testdata/discovery/bar_endpoint.json
endpoints/test/testdata/discovery/foo_endpoint.json
endpoints/test/testdata/discovery/multiple_parameter_endpoint.json
endpoints/test/testdata/discovery/namespace.json

* include required query parameters in parameterOrder
* updated icon urls
* including API description, title, documentation link, and canonical name
* stringify default values in the discovery doc
Includes two new tests ported from the Java version of the framework.

Several discovery document fixes

---

endpoints/test/users_id_token_test.py
endpoints/users_id_token.py

When running in the devappserver, we have to verify oauth tokens using Google's tokeninfo api. This brings the codebase up to date with [v3 of the API](https://developers.google.com/identity/protocols/OAuth2UserAgent#validate-access-token).
Fixes #157.

Update local oauth path to use v3 tokeninfo api

---

endpoints/__init__.py

Rationale: Removed last use of obsolete discovery doc remote service.

Bump minor version (4.4.1 -> 4.5.0)

---

endpoints/__init__.py
endpoints/apiserving.py
endpoints/endpoints_dispatcher.py
endpoints/users_id_token.py

Package loggers will now have a default logging level of INFO, meaning the DEBUG-level log statements will not be shown.
This is easily overridden in customer code with something like this:
`logging.getLogger('endpoints').setLevel(logging.DEBUG)`
Additionally, some logging levels have been corrected.

Logging overhaul

---

endpoints/__init__.py
endpoints/apiserving.py

Rationale: Don't use package name for internal imports

Bump subminor version (4.6.0 -> 4.6.1)

---

endpoints/openapi_generator.py
test/openapi_generator_test.py

If a ResourceContainer has a positional argument, that is treated as a body message. But GET/DELETE requests can't take a request body. This raises an informative error; previously an uninformative KeyError was raised.
Fixes #167.

Better error when request body found for GET/DELETE method.

---

endpoints/openapi_generator.py
test/openapi_generator_test.py

If a method takes a request body, you can't omit that; it's effectively required. We should mark it as such so swagger-codegen will generate code properly.
Fixes #173.

Body parameters are required.

---

endpoints/discovery_generator.py
test/discovery_document_test.py
test/discovery_generator_test.py
test/testdata/discovery/bar_endpoint.json
test/testdata/discovery/multiple_parameter_endpoint.json

Discovery docs will now send boolean default values such that they will be correctly written into Java clients. Additionally, the namespace attributes such as `owner_domain` will be respected when set on the API instead of inside a namespace object.

Discovery document / client generation fixes
